version: "3.8"

services:
  # ===================
  # Base de datos
  # ===================
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tingeso
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./data/dataInsert.sql:/docker-entrypoint-initdb.d/02-dataInsert.sql:ro
    networks:
      - mynet

  # ===================
  # BACKEND (3 instancias)
  # ===================
  backend1:
    image: pbust0sn/toolrent-backend:latest
    pull_policy: always
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
      IMAGE_UPLOAD_DIR: /uploads
    depends_on:
      - mysql
      - keycloak
    volumes:
      - ./uploads:/uploads
    networks:
      - mynet
    restart: unless-stopped

  backend2:
    image: pbust0sn/toolrent-backend:latest
    pull_policy: always
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
      IMAGE_UPLOAD_DIR: /uploads
    depends_on:
      - mysql
      - keycloak
    volumes:
      - ./uploads:/uploads
    networks:
      - mynet
    restart: unless-stopped

  backend3:
    image: pbust0sn/toolrent-backend:latest
    pull_policy: always
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
      IMAGE_UPLOAD_DIR: /uploads
    depends_on:
      - mysql
      - keycloak
    volumes:
      - ./uploads:/uploads
    networks:
      - mynet
    restart: unless-stopped

  # ===================
  # FRONTEND
  # ===================
  frontend:
    build: ./monoliticoFrontend
    image: pbust0sn/toolrent-frontend:latest
    pull_policy: always
    networks:
      - mynet

  # ===================
  # Nginx para balancear frontend
  # ===================
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "80:80"   # frontend
        - "443:443" # backend
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt:ro
        - ./monoliticoFrontend/certs:/etc/nginx/certs:ro
        - ./monoliticoFrontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - frontend
        - backend1
        - backend2
        - backend3
      networks:
        - mynet

  # ===================
  # Keycloak
  # ===================
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    command: start-dev --import-realm --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: 15.229.27.254
      LANG: C.UTF-8
      LC_ALL: C.UTF-8 
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "true"
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - mysql
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - mynet

# ===================
# Redes
# ===================
networks:
  mynet:
    driver: bridge
