version: "3.8"

services:
  # Base de datos
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tingeso
    ports:
      - "3306:3306"
    networks:
      - mynet

  # ===================
  # BACKEND (3 instancias)
  # ===================
  backend1:
    image: pbust0sn/toolrent-backend:latest
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend-network
      - mynet

  backend2:
    image: pbust0sn/toolrent-backend:latest
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend-network
      - mynet

  backend3:
    image: pbust0sn/toolrent-backend:latest
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend-network
      - mynet

  # ===================
  # FRONTEND (3 instancias)
  # ===================
  frontend1:
    image: pbust0sn/toolrent-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: pbust0sn/toolrent-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: pbust0sn/toolrent-frontend:latest
    networks:
      - frontend-network

  # ===================
  # Nginx para balancear frontend
  # ===================
  nginx-frontend:
    build:
      context: ./monoliticoFrontend
    container_name: nginx_frontend
    ports:
      - "8070:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # ===================
  # Nginx para balancear backend
  # ===================
  nginx-backend:
    image: nginx:latest
    container_name: nginx_backend
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network
      - mynet

  # ===================
  # Keycloak
  # ===================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: tingeso
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: start-dev
    networks:
      - mynet

# ===================
# Redes
# ===================
networks:
  frontend-network:
  backend-network:
  mynet:
    driver: bridge
