apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  labels:
    app: eureka-service-deployment
spec:
  selector:
    matchLabels:
      app: eureka-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service-deployment
    spec:
      containers:
        - name: eureka-service
          image: pbust0sn/eureka-service:latest
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /eureka/
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /eureka/
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-service-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: nodePort