spring:
  application:
    name: ms-reports-service

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}
