server:
  port: 8080
  ssl:
    key-store: file:/app/certs/tls.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://192.168.39.157:30443/realms/toolrent
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
            exposedHeaders:
              - "Content-Type"
              - "X-Total-Count"
      routes:
        # Loans Microservice
        - id: loans-service
          uri: lb://ms-loans-service
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=2

        # Clients Microservice
        - id: clients-service
          uri: lb://ms-clients-service
          predicates:
            - Path=/api/clients/**

        # Inventory/Tools Microservice
        - id: inventory-service
          uri: lb://ms-inventory-service
          predicates:
            - Path=/api/tools/**,/api/inventory/**
          filters:
            - StripPrefix=2

        # Rates/Fines Microservice
        - id: rates-service
          uri: lb://ms-rates-service
          predicates:
            - Path=/api/fines/**,/api/rates/**
          filters:
            - StripPrefix=2

        # Kardex/Records Microservice
        - id: kardex-service
          uri: lb://ms-kardex-service
          predicates:
            - Path=/api/records/**,/api/kardex/**
          filters:
            - StripPrefix=2

        # Reports Microservice
        - id: reports-service
          uri: lb://ms-reports-service
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=2

        # Users Microservice
        - id: users-service
          uri: lb://ms-users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true