# Keycloak Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3.4
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /opt/keycloak/data/import/realm-export.json
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "false"
            - name: KC_HTTPS_ENABLED
              value: "true"
            - name: KC_HTTPS_PORT
              value: "8443"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /etc/keycloak/certs/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /etc/keycloak/certs/tls.key
            - name: KC_PROXY
              value: edge
          ports:
            - containerPort: 8080
            - containerPort: 8443
          args:
            - start-dev
            - --import-realm
          volumeMounts:
            - name: realm-volume
              mountPath: /opt/keycloak/data/import
            - name: keycloak-certs
              mountPath: /etc/keycloak/certs
          resources:
            requests:
              memory: "512Mi"
              cpu: "4"
            limits:
              memory: "1G"
              cpu: "8"
      volumes:
        - name: realm-volume
          configMap:
            name: keycloak-realm-config
        - name: keycloak-certs
          secret:
            secretName: keycloak-tls
---
# Keycloak Service
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30081
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
      nodePort: 30443
  selector:
    app: keycloak