# Keycloak Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3.4
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /opt/keycloak/data/import/realm-export.json
            - name: KC_LOG_LEVEL
              value: DEBUG

            - containerPort: 8080
          args:
            - start-dev
            - --import-realm
          volumeMounts:
            - name: realm-volume
              mountPath: /opt/keycloak/data/import
          resources:
            requests:
              memory: "512Mi"
              cpu: "4"
            limits:
              memory: "1G"
              cpu: "8"
      volumes:
        - name: realm-volume
          configMap:
            name: keycloak-realm-config
---
# Keycloak Service
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: keycloak