apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: default
data:
  realm-export.json: |
    {
      "id": "060efaeb-1765-42fa-abfb-e99a01fdc922",
      "realm": "toolRent",
      "notBefore": 0,
      "defaultSignatureAlgorithm": "RS256",
      "revokeRefreshToken": false,
      "refreshTokenMaxReuse": 0,
      "accessTokenLifespan": 300,
      "accessTokenLifespanForImplicitFlow": 900,
      "ssoSessionIdleTimeout": 1800,
      "ssoSessionMaxLifespan": 36000,
      "ssoSessionIdleTimeoutRememberMe": 0,
      "ssoSessionMaxLifespanRememberMe": 0,
      "offlineSessionIdleTimeout": 2592000,
      "offlineSessionMaxLifespanEnabled": false,
      "offlineSessionMaxLifespan": 5184000,
      "clientSessionIdleTimeout": 0,
      "clientSessionMaxLifespan": 0,
      "clientOfflineSessionIdleTimeout": 0,
      "clientOfflineSessionMaxLifespan": 0,
      "accessCodeLifespan": 60,
      "accessCodeLifespanUserAction": 300,
      "accessCodeLifespanLogin": 1800,
      "actionTokenGeneratedByAdminLifespan": 43200,
      "actionTokenGeneratedByUserLifespan": 300,
      "oauth2DeviceCodeLifespan": 600,
      "oauth2DevicePollingInterval": 5,
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "registrationEmailAsUsername": false,
      "rememberMe": false,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": false,
      "editUsernameAllowed": false,
      "bruteForceProtected": false,
      "permanentLockout": false,
      "maxTemporaryLockouts": 0,
      "bruteForceStrategy": "MULTIPLE",
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 30,
      "roles": {
        "realm": [
          {
            "id": "28359086-b578-44e1-8598-f914671825ef",
            "name": "offline_access",
            "description": "${role_offline-access}",
            "composite": false,
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          },
          {
            "id": "def4ef28-6b66-4f57-8920-c086077d9056",
            "name": "ADMIN",
            "description": "",
            "composite": false,
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          },
          {
            "id": "36eb6d9b-16e4-4eb5-80fb-061f315621e0",
            "name": "uma_authorization",
            "description": "${role_uma_authorization}",
            "composite": false,
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          },
          {
            "id": "ff36a4ad-1d88-422b-91fd-6b181c5a5478",
            "name": "STAFF",
            "description": "",
            "composite": false,
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          },
          {
            "id": "92163851-664d-4247-8439-2b1cc3a075e5",
            "name": "CLIENT",
            "description": "",
            "composite": false,
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          },
          {
            "id": "a0e47ab6-acef-4690-b909-133906f827fa",
            "name": "default-roles-toolrent",
            "description": "${role_default-roles}",
            "composite": true,
            "composites": {
              "realm": [
                "offline_access",
                "uma_authorization"
              ],
              "client": {
                "account": [
                  "view-profile",
                  "manage-account"
                ]
              }
            },
            "clientRole": false,
            "containerId": "060efaeb-1765-42fa-abfb-e99a01fdc922",
            "attributes": {}
          }
        ]
      }
    }